rails:
  image: xxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/compose-test
  command: "sh /app/wait.sh bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - /app/vendor
  mem_limit: 268435456
  ports:
    - "80:3000"
  links:
    - db
  environment:
    - DATABASE_HOST=db
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=""
  log_driver: awslogs
  log_opt:
    awslogs-group: "compose-test-web-logs"
    awslogs-region: "ap-northeast-1"
db:
  image: postgres:9.6-alpine
  mem_limit: 268435456
  volumes:
    - /var/lib/postgresql/data
  ports:
    - "5432:5432"
  log_driver: awslogs
  log_opt:
    awslogs-group: "compose-test-db-logs"
    awslogs-region: "ap-northeast-1"
